title: Gone Fishing
description: Tireless tourist with a camera.
baseurl: ""
url: "https://www.gone-fishing.net"
author:
  name: Matthias Mullie
  email: gonefishing@mullie.eu
  twitter: bloggonefishing
  instagram: matthiasmullie
  facebook: bloggonefishing
maps:
  key: AIzaSyCIy1AW6TTYzls2iig8R-eNNLtZnmirri0

markdown: kramdown
theme: minima
paginate: 10
paginate_path: "/travels/page:num/"
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap
exclude:
  - travels/_posts/*.wip
  - Gemfile
  - Gemfile.lock

permalink: /:categories/:title/

defaults:
  - scope:
      path: "photos/full"
    values:
      photo: true

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  parmalinks:
    tag: '/tag/:name'
