title: Gone Fishing
description: My friends call me super tourist for a reason. This is an account of my travels.
baseurl: "/"
url: "https://www.gone-fishing.net"
author:
  name: Matthias Mullie
  email: gonefishing@mullie.eu
  twitter: matthiasmullie
  instagram: matthiasmullie
  gplus: https://plus.google.com/u/0/114103174273569238978
maps:
  key: AIzaSyCIy1AW6TTYzls2iig8R-eNNLtZnmirri0

markdown: kramdown
theme: minima
paginate: 10
paginate_path: "/stories/page:num/"
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:categories/:title/

defaults:
  - scope:
      path: "photos/large"
    values:
      photo: true

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  parmalinks:
    tag: '/tag/:name'
